### ISSUE TITLE
Layout of Lock Icon in USWDS Banner

### ISSUE THREAD

**Issue by elisoncrum** [marinecoders/marines.dev#10]
## Summary
Following *every* USWDS standard and essentially scraping the HTML from USWDS causes certain layout issues.

## Fix Action
Use 🔒 emoji and set it to be just white. Remove SVG.

```css
lock {
  color: transparent;  
  text-shadow: 0 0 0 white;
}
```

## Screenshot
![Screenshot from 2022-09-24 18-09-14](https://user-images.githubusercontent.com/30413278/192124047-c3230fb4-06e4-4338-974c-04b3c5677cb5.png)
